server:
  forward-headers-strategy: framework
  servlet:
    context-path: /${REPO_NAME}
spring:
  config:
    import:
      - aws-secretsmanager:${ENV}/${PROJECT_NAME}/smtp
      - aws-secretsmanager:${ENV}/${PROJECT_NAME}/s3
      - aws-secretsmanager:${ENV}/${PROJECT_NAME}/kafka
      - aws-secretsmanager:${ENV}/${PROJECT_NAME}/oauth2
      - aws-secretsmanager:${ENV}/${PROJECT_NAME}/gis
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:auth-service}
  datasource:
    url: ${DATABASE_URL}
    username: ${AWS_RDS_SECRET_NAME:${DATABASE_USERNAME}}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER:com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver}
    hikari:
      allow-pool-suspension: true
      maximum-pool-size: ${MAX_POOL_SIZE:10}
      minimum-idle: ${MIN_IDLE:10}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  cloud:
    kubernetes:
      discovery:
        enabled: ${KUBERNETES_ENABLED:true}
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
      client:
        config:
          auth-service:
            url: ${AUTH_SERVICE_URL:#{null}}
          auth-internal-service:
            url: ${AUTH_INTERNAL_SERVICE_URL:#{null}}
          common-service:
            url: ${COMMON_SERVICE_URL:#{null}}
          common-internal-service:
            url: ${COMMON_INTERNAL_SERVICE_URL:#{null}}
          user-service:
            url: ${USER_SERVICE_URL:#{null}}
          user-internal-service:
            url: ${USER_INTERNAL_SERVICE_URL:#{null}}
          venue-service:
            url: ${VENUE_SERVICE_URL:#{null}}
          venue-internal-service:
            url: ${VENUE_INTERNAL_SERVICE_URL:#{null}}
          interestgroup-service:
            url: ${INTERESTGROUP_SERVICE_URL:#{null}}
          interestgroup-internal-service:
            url: ${INTERESTGROUP_INTERNAL_SERVICE_URL:#{null}}
          event-service:
            url: ${EVENT_SERVICE_URL:#{null}}
          event-internal-service:
            url: ${EVENT_INTERNAL_SERVICE_URL:#{null}}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.fancia.backend.shared.user.core.message
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:fancia-kafka-fancia.f.aivencloud.com:25067}
    properties:
      security.protocol: SSL
      ssl.truststore.type: PEM
      ssl.keystore.type: PEM
      ssl.truststore.certificates: ${KAFKA_SSL_TRUSTSTORE_CERTIFICATES}
      ssl.keystore.certificate.chain: ${KAFKA_SSL_KEYSTORE_CERTIFICATE_CHAIN}
      ssl.keystore.key: ${KAFKA_SSL_KEYSTORE_KEY}
      auto.register.schemas: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      gis_admin_password: ${GIS_ADMIN_PASSWORD}
app:
  application-name: ${PROJECT_NAME}-backend-${REPO_NAME}
  base-url: ${DOMAIN_NAME}/${REPO_NAME}/api
  login-page-url: ${AUTH_SERVICE_URL:auth-service}/login
  s3:
    bucket-name: ${BUCKET_NAME}
    access-key: ${BUCKET_ACCESS_KEY}
    secret-key: ${BUCKET_SECRET_KEY}
    base-url: ${BUCKET_ENDPOINT}
    region: ${AWS_REGION}
    storage-class: STANDARD

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true


logging:
  level:
    com.fancia.backend.venue.config.FeignConfig: DEBUG
