server:
  servlet:
    context-path: /${REPO_NAME}
spring:
  config:
    import:
      - optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:auth-service}
  datasource:
    url: ${DATABASE_URL}
    username: ${AWS_RDS_SECRET_NAME:${DATABASE_USERNAME}}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER:com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/db/migration/V1__create_schema.sql
              create-source: metadata
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  cloud:
    aws:
      secretsmanager:
        endpoint: http://localhost:4566
        region: ${AWS_REGION}
      credentials:
        access-key: test
        secret-key: test
      s3:
        endpoint: http://localhost:4566
        region: ${AWS_REGION}
        credentials:
          access-key: ${BUCKET_ACCESS_KEY}
          secret-key: ${BUCKET_SECRET_KEY}
    kubernetes:
      discovery:
        enabled: ${KUBERNETES_ENABLED:true}
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
      client:
        config:
          auth-service:
            url: ${AUTH_SERVICE_URL:#{null}}
          auth-internal-service:
            url: ${AUTH_INTERNAL_SERVICE_URL:#{null}}
          common-service:
            url: ${COMMON_SERVICE_URL:#{null}}
          common-internal-service:
            url: ${COMMON_INTERNAL_SERVICE_URL:#{null}}
          user-service:
            url: ${USER_SERVICE_URL:#{null}}
          user-internal-service:
            url: ${USER_INTERNAL_SERVICE_URL:#{null}}
          venue-service:
            url: ${VENUE_SERVICE_URL:#{null}}
          venue-internal-service:
            url: ${VENUE_INTERNAL_SERVICE_URL:#{null}}
          interestgroup-service:
            url: ${INTERESTGROUP_SERVICE_URL:#{null}}
          interestgroup-internal-service:
            url: ${INTERESTGROUP_INTERNAL_SERVICE_URL:#{null}}
          event-service:
            url: ${EVENT_SERVICE_URL:#{null}}
          event-internal-service:
            url: ${EVENT_INTERNAL_SERVICE_URL:#{null}}
  kafka:
    listener:
      auto-startup: false
    admin:
      auto-create: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.fancia.backend.shared.user.core.message
    bootstrap-servers: bootstrap.${DOMAIN_NAME}:9094
  flyway:
    locations: classpath:db/migration
    placeholders:
      gis_admin_password: ${GIS_ADMIN_PASSWORD}
app:
  application-name: ${PROJECT_NAME}-backend-${REPO_NAME}
  base-url: ${DOMAIN_NAME}/${REPO_NAME}/api
  login-page-url: ${AUTH_SERVICE_URL:auth-service}/login
  s3:
    bucket-name: ${BUCKET_NAME}
    access-key: ${BUCKET_ACCESS_KEY}
    secret-key: ${BUCKET_SECRET_KEY}
    base-url: ${BUCKET_ENDPOINT}
    region: ${AWS_REGION}
    storage-class: STANDARD

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true


logging:
  level:
    root: DEBUG
    com.fancia.backend.venue.external.CommonInternalClient: DEBUG
    com.fancia.backend.venue.config.FeignConfig: DEBUG
